pstmd ready. simple.

diff --git a/pstmd b/pstmd
--- a/pstmd
+++ b/pstmd
@@ -1,26 +1,23 @@
 #!/bin/bash
 
-# TODO: Exclude own pid from the ps tree
-# TODO: Lock
+if [ $# -ne 1 ]; then
+  (
+    echo "ERROR: Invalid arguments"
+    echo "Usage: $0 <prob-directory>"
+    echo ""
+    echo "<prob-directory>  is where you want pstmd to ls and write the log"
+
+  ) >&2
+
+  exit 1
+fi
+
+MON_HOME=$1
+cd $MON_HOME
 
 while :; do
-  MON_HOME=$1
+  ls . > /dev/null
+  date | tee -a log
 
-  cd $MON_HOME/$HOSTNAME
-
-  #ps -o uid,user,pid,pcpu,pmem,start_time,cmd --forest -e > /tmp/ps-$HOSTNAME;
-  #cp /tmp/ps-$HOSTNAME  .
-
-  #ss -ap > /tmp/pstm-ss-${HOSTNAME}
-  #cp /tmp/pstm-ss-${HOSTNAME} .
-
-  rm -f .git/index.lock
-  git add . ;
-  git commit -m "auto from $HOSTNAME" > /dev/null ;
-  #git gc --auto
-
-  ls ~alevchuk /home > /dev/null ;
-
-  date | tee log;
-  sleep 1 ;
+  sleep 1
 done
